### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by CloudyMN1979** [Space-Chemist/DevPlugin#3]
There is no instruction anywhere on github or steam on how to install this plugin.  Simply using the ingame modloader throws an error.

**Comment by Space-Chemist** [comment]
I will add instructions but it is meant to be used in the same manner as other plugins using torch. Put the plugin zip in the plugins folder the copy the guid into the torch.cfg between plugins tag  also make guid lower case. The plugin should work as intended use as intended. This is not a mod but a tool to use with a mod for community servers.
